# Generated by Django 5.1.1 on 2025-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshHire', '0002_alter_employerprofile_user_alter_seekerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
