# Generated by Django 5.1.1 on 2025-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshHire', '0004_alter_employerprofile_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(null=True),
        ),
    ]
